account_id = "19a745c88f8264f29c608584b7e417ab"
compatibility_date = "2022-09-22"
main = "./src/index.js"
name = "atomic-url"

kv_namespaces = [
  {binding = "URL_DB", id = "bf98832a3f6e45e18f3c39b6db1d329a", preview_id = "bf98832a3f6e45e18f3c39b6db1d329a"},
]
workers_dev = true

[vars]
URL_CACHE = "apiCache" 
URL_EXPIRATION_TTL = 3600 # seconds

[dev]
ip = "0.0.0.0"
local_protocol = "http"
port = 8787
upstream_protocol = "https"

[env.staging]
kv_namespaces = [
  {binding = "URL_DB", id = "bf98832a3f6e45e18f3c39b6db1d329a"},
]
name = "atomic-url-staging"
workers_dev = true
[env.staging.vars]
URL_CACHE = "apiCache" 
URL_EXPIRATION_TTL = 3600 # seconds

[env.production]
kv_namespaces = [
  {binding = "URL_DB", id = "709b8cf5ddf74f739f1535c34ff0634b"},
]
name = "atomic-url"
route = "s.jerrynsh.com/*"
workers_dev = false
[env.production.vars]
URL_CACHE = "apiCache" 
URL_EXPIRATION_TTL = 3600 # seconds
